// This file was generated by script/generate.py
#ifndef LIBPNG_LOADER_H
#define LIBPNG_LOADER_H

#include <setjmp.h>
#include <stdint.h>
#include <stdio.h>
#include <time.h>

// ------ Loader's API ------

/**
 * Configuration for `libpng_load()`.
 *
 * @enum libpng_load_flags
 */
typedef unsigned int libpng_load_flags;
enum {
    LIBPNG_LOAD_FLAGS_UNSAFE = 0,  //!< Disable all validatiors.
    LIBPNG_LOAD_FLAGS_VERSION_CHECK = 1,  //!< Check the version string of user's libpng.
    LIBPNG_LOAD_FLAGS_FUNCTION_CHECK = 2,  //!< Ensure all function pointers are non-NULL.
    LIBPNG_LOAD_FLAGS_PRINT_ERRORS = 4,  //!< Output error messages to stderr.
};
#define LIBPNG_LOAD_FLAGS_DEFAULT ( \
    LIBPNG_LOAD_FLAGS_VERSION_CHECK | \
    LIBPNG_LOAD_FLAGS_FUNCTION_CHECK)

/**
 * Error code for `libpng_load()`.
 *
 * @enum libpng_load_error
 */
typedef unsigned int libpng_load_error;
enum {
    LIBPNG_SUCCESS = 0,
    LIBPNG_ERROR_LIBPNG_NOT_FOUND,  //!< libpng was not found.
    LIBPNG_ERROR_LIBPNG_INVALID_ELF,  //!< libpng was not built for your platform.
    LIBPNG_ERROR_LIBPNG_FAIL,  //!< failed to load libpng due to other reasons.
    LIBPNG_ERROR_LIBZ_NOT_FOUND,  //!< libz was not found.
    LIBPNG_ERROR_FUNCTION_NOT_FOUND = 32,  //!< a function was not loaded successfully.
    LIBPNG_ERROR_VERSION_MISMATCH,  //!< user's libpng has an unexpected version string.
    LIBPNG_ERROR_LOADED_ALREADY,  //!< libpng was loaded already.
    LIBPNG_ERROR_NULL_REFERENCE,  //!< library path was not specified.
    LIBPNG_ERROR_MAX
};

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Load libpng and its functions.
 * You can use `png_*` functions after loading libpng successfully.
 *
 * @note: If you get `LIBPNG_ERROR_VERSION_MISMATCH`,
 *        you can check the version string with
 *        `libpng_get_user_ver()` and `libpng_get_loader_ver()`.
 *
 * @param flags Configuration flags. Use `LIBPNG_FLAGS_DEFAULT` to enable validations.
 * @returns `LIBPNG_SUCCESS` if all functions are loaded, `LIBPNG_ERROR_*` otherwise.
 */
libpng_load_error libpng_load(libpng_load_flags flags);

/**
 * Free libpng and initialize function pointers.
 *
 * @note: `libpng_free()` does not initialize the version string buffer.
 *        `libpng_get_user_ver()` is still available after closing libpng.
 */
void libpng_free(void);

/**
 * Return if libpng is loaded or not.
 *
 * @returns 1 if libpng is loaded, 0 otherwise.
 */
int libpng_is_loaded(void);

/**
 * Return `PNG_LIBPNG_VER_STRING` written in user's libpng.
 * It should be of the form `xx.yy.zz.str`. (e.g. `1.8.0.git`)
 *
 * @note: The `xx.yy` part should be the same as `libpng_get_loader_ver()`
 *        to get `libpng_load()` to work.
 *
 * @returns A string that represents the version of user's libpng.
 */
const char* libpng_get_user_ver(void);

/**
 * Return `PNG_LIBPNG_VER_STRING` written in `libpng-loader.h`.
 * It should be of the form `xx.yy.zz.str`. (e.g. `1.6.54.libpng-loader`)
 *
 * @note: The `xx.yy` part should be the same as `libpng_get_user_ver()`
 *        to get `libpng_load()` to work.
 *
 * @returns A string that represents the expected version of libpng.
 */
const char* libpng_get_loader_ver(void);

/**
 * Outputs missing functions into stdout
 *
 * @param stream A stream pointer (e.g. stdout) to output messages.
 * @param show_optional Prints all missing APIs when 1.
 *                      Removes optional APIs from the list when 0.
 */
void libpng_print_missing_functions(FILE *stream, int show_optional);

#ifdef __cplusplus
}
#endif

// ------ Structs ------

typedef void png_void;
typedef char png_char;
typedef uint8_t png_byte;
typedef int16_t png_int_16;
typedef uint16_t png_uint_16;
typedef int32_t png_int_32;
typedef uint32_t png_uint_32;
typedef size_t png_size_t;
typedef size_t png_alloc_size_t;
typedef png_int_32 png_fixed_point;
typedef double png_double;

typedef struct png_struct_def png_struct;
typedef png_struct *png_structp;

typedef struct png_info_def png_info;
typedef png_info *png_infop;

typedef struct png_control_def png_control;
typedef png_control *png_controlp;

typedef struct png_color_struct {
    png_byte red;
    png_byte green;
    png_byte blue;
} png_color;

typedef struct png_color_16_struct {
    png_byte index;
    png_uint_16 red;
    png_uint_16 green;
    png_uint_16 blue;
    png_uint_16 gray;
} png_color_16;

typedef struct png_color_8_struct {
    png_byte red;
    png_byte green;
    png_byte blue;
    png_byte gray;
    png_byte alpha;
} png_color_8;

typedef struct png_sPLT_entry_struct {
    png_uint_16 red;
    png_uint_16 green;
    png_uint_16 blue;
    png_uint_16 alpha;
    png_uint_16 frequency;
} png_sPLT_entry;

typedef struct png_sPLT_struct {
    png_char * name;
    png_byte depth;
    png_sPLT_entry * entries;
    png_int_32 nentries;
} png_sPLT_t;

typedef struct png_text_struct {
    int compression;
    png_char * key;
    png_char * text;
    size_t text_length;
    size_t itxt_length;
    png_char * lang;
    png_char * lang_key;
} png_text;

typedef struct png_time_struct {
    png_uint_16 year;
    png_byte month;
    png_byte day;
    png_byte hour;
    png_byte minute;
    png_byte second;
} png_time;

typedef struct png_unknown_chunk_t {
    png_byte name[5];
    png_byte *data;
    size_t size;
    png_byte location;
} png_unknown_chunk;

typedef struct png_row_info_struct {
    png_uint_32 width;
    size_t rowbytes;
    png_byte color_type;
    png_byte bit_depth;
    png_byte channels;
    png_byte pixel_depth;
} png_row_info;

typedef struct {
    png_control * opaque;
    png_uint_32 version;
    png_uint_32 width;
    png_uint_32 height;
    png_uint_32 format;
    png_uint_32 flags;
    png_uint_32 colormap_entries;
    png_uint_32 warning_or_error;
    char message[64];
} png_image, *png_imagep;

// ------ Macros ------

#define PNG_H
#define PNG_LIBPNG_VER_STRING "1.6.53"
#define PNG_HEADER_VERSION_STRING " libpng version " PNG_LIBPNG_VER_STRING "\n"
#define PNG_LIBPNG_VER_SHAREDLIB 16
#define PNG_LIBPNG_VER_SONUM     PNG_LIBPNG_VER_SHAREDLIB
#define PNG_LIBPNG_VER_DLLNUM    PNG_LIBPNG_VER_SHAREDLIB
#define PNG_LIBPNG_VER_MAJOR   1
#define PNG_LIBPNG_VER_MINOR   6
#define PNG_LIBPNG_VER_RELEASE 53
#define PNG_LIBPNG_VER_BUILD 0
#define PNG_LIBPNG_BUILD_ALPHA               1
#define PNG_LIBPNG_BUILD_BETA                2
#define PNG_LIBPNG_BUILD_RC                  3
#define PNG_LIBPNG_BUILD_STABLE              4
#define PNG_LIBPNG_BUILD_RELEASE_STATUS_MASK 7
#define PNG_LIBPNG_BUILD_PATCH    8
#define PNG_LIBPNG_BUILD_PRIVATE 16
#define PNG_LIBPNG_BUILD_SPECIAL 32
#define PNG_LIBPNG_BUILD_BASE_TYPE PNG_LIBPNG_BUILD_STABLE
#define PNG_LIBPNG_VER 10653
#define png_libpng_ver png_get_header_ver(NULL)
#define PNG_TEXT_COMPRESSION_NONE_WR -3
#define PNG_TEXT_COMPRESSION_zTXt_WR -2
#define PNG_TEXT_COMPRESSION_NONE    -1
#define PNG_TEXT_COMPRESSION_zTXt     0
#define PNG_ITXT_COMPRESSION_NONE     1
#define PNG_ITXT_COMPRESSION_zTXt     2
#define PNG_TEXT_COMPRESSION_LAST     3
#define PNG_HAVE_IHDR  0x01
#define PNG_HAVE_PLTE  0x02
#define PNG_AFTER_IDAT 0x08
#define PNG_UINT_31_MAX ((png_uint_32)0x7fffffffL)
#define PNG_UINT_32_MAX ((png_uint_32)(-1))
#define PNG_SIZE_MAX ((size_t)(-1))
#define PNG_FP_1    100000
#define PNG_FP_HALF  50000
#define PNG_FP_MAX  ((png_fixed_point)0x7fffffffL)
#define PNG_FP_MIN  (-PNG_FP_MAX)
#define PNG_COLOR_MASK_PALETTE    1
#define PNG_COLOR_MASK_COLOR      2
#define PNG_COLOR_MASK_ALPHA      4
#define PNG_COLOR_TYPE_GRAY 0
#define PNG_COLOR_TYPE_PALETTE  (PNG_COLOR_MASK_COLOR | PNG_COLOR_MASK_PALETTE)
#define PNG_COLOR_TYPE_RGB        (PNG_COLOR_MASK_COLOR)
#define PNG_COLOR_TYPE_RGB_ALPHA  (PNG_COLOR_MASK_COLOR | PNG_COLOR_MASK_ALPHA)
#define PNG_COLOR_TYPE_GRAY_ALPHA (PNG_COLOR_MASK_ALPHA)
#define PNG_COLOR_TYPE_RGBA  PNG_COLOR_TYPE_RGB_ALPHA
#define PNG_COLOR_TYPE_GA  PNG_COLOR_TYPE_GRAY_ALPHA
#define PNG_COMPRESSION_TYPE_BASE 0
#define PNG_COMPRESSION_TYPE_DEFAULT PNG_COMPRESSION_TYPE_BASE
#define PNG_FILTER_TYPE_BASE      0
#define PNG_INTRAPIXEL_DIFFERENCING 64
#define PNG_FILTER_TYPE_DEFAULT   PNG_FILTER_TYPE_BASE
#define PNG_INTERLACE_NONE        0
#define PNG_INTERLACE_ADAM7       1
#define PNG_INTERLACE_LAST        2
#define PNG_OFFSET_PIXEL          0
#define PNG_OFFSET_MICROMETER     1
#define PNG_OFFSET_LAST           2
#define PNG_EQUATION_LINEAR       0
#define PNG_EQUATION_BASE_E       1
#define PNG_EQUATION_ARBITRARY    2
#define PNG_EQUATION_HYPERBOLIC   3
#define PNG_EQUATION_LAST         4
#define PNG_SCALE_UNKNOWN         0
#define PNG_SCALE_METER           1
#define PNG_SCALE_RADIAN          2
#define PNG_SCALE_LAST            3
#define PNG_RESOLUTION_UNKNOWN    0
#define PNG_RESOLUTION_METER      1
#define PNG_RESOLUTION_LAST       2
#define PNG_sRGB_INTENT_PERCEPTUAL 0
#define PNG_sRGB_INTENT_RELATIVE   1
#define PNG_sRGB_INTENT_SATURATION 2
#define PNG_sRGB_INTENT_ABSOLUTE   3
#define PNG_sRGB_INTENT_LAST       4
#define PNG_KEYWORD_MAX_LENGTH     79
#define PNG_MAX_PALETTE_LENGTH    256
#define PNG_INFO_gAMA 0x0001U
#define PNG_INFO_sBIT 0x0002U
#define PNG_INFO_cHRM 0x0004U
#define PNG_INFO_PLTE 0x0008U
#define PNG_INFO_tRNS 0x0010U
#define PNG_INFO_bKGD 0x0020U
#define PNG_INFO_hIST 0x0040U
#define PNG_INFO_pHYs 0x0080U
#define PNG_INFO_oFFs 0x0100U
#define PNG_INFO_tIME 0x0200U
#define PNG_INFO_pCAL 0x0400U
#define PNG_INFO_sRGB 0x0800U
#define PNG_INFO_iCCP 0x1000U
#define PNG_INFO_sPLT 0x2000U
#define PNG_INFO_sCAL 0x4000U
#define PNG_INFO_IDAT 0x8000U
#define PNG_INFO_eXIf 0x10000U
#define PNG_INFO_cICP 0x20000U
#define PNG_INFO_cLLI 0x40000U
#define PNG_INFO_mDCV 0x80000U
#define PNG_INFO_acTL 0x100000U
#define PNG_INFO_fcTL 0x200000U
#define PNG_INFO_fdAT 0x400000U
#define PNG_TRANSFORM_IDENTITY       0x0000
#define PNG_TRANSFORM_STRIP_16       0x0001
#define PNG_TRANSFORM_STRIP_ALPHA    0x0002
#define PNG_TRANSFORM_PACKING        0x0004
#define PNG_TRANSFORM_PACKSWAP       0x0008
#define PNG_TRANSFORM_EXPAND         0x0010
#define PNG_TRANSFORM_INVERT_MONO    0x0020
#define PNG_TRANSFORM_SHIFT          0x0040
#define PNG_TRANSFORM_BGR            0x0080
#define PNG_TRANSFORM_SWAP_ALPHA     0x0100
#define PNG_TRANSFORM_SWAP_ENDIAN    0x0200
#define PNG_TRANSFORM_INVERT_ALPHA   0x0400
#define PNG_TRANSFORM_STRIP_FILLER   0x0800
#define PNG_TRANSFORM_STRIP_FILLER_BEFORE PNG_TRANSFORM_STRIP_FILLER
#define PNG_TRANSFORM_STRIP_FILLER_AFTER 0x1000
#define PNG_TRANSFORM_GRAY_TO_RGB   0x2000
#define PNG_TRANSFORM_EXPAND_16     0x4000
#define PNG_TRANSFORM_SCALE_16      0x8000
#define PNG_FLAG_MNG_EMPTY_PLTE     0x01
#define PNG_FLAG_MNG_FILTER_64      0x04
#define PNG_ALL_MNG_FEATURES        0x05
#define png_check_sig(sig, n) (png_sig_cmp((sig), 0, (n)) == 0)
#define PNG_ERROR_ACTION_NONE  1
#define PNG_ERROR_ACTION_WARN  2
#define PNG_ERROR_ACTION_ERROR 3
#define PNG_RGB_TO_GRAY_DEFAULT (-1)
#define PNG_ALPHA_PNG           0
#define PNG_ALPHA_STANDARD      1
#define PNG_ALPHA_ASSOCIATED    1
#define PNG_ALPHA_PREMULTIPLIED 1
#define PNG_ALPHA_OPTIMIZED     2
#define PNG_ALPHA_BROKEN        3
#define PNG_DEFAULT_sRGB -1
#define PNG_GAMMA_MAC_18 -2
#define PNG_GAMMA_sRGB   220000
#define PNG_GAMMA_LINEAR PNG_FP_1
#define PNG_FILLER_BEFORE 0
#define PNG_FILLER_AFTER 1
#define PNG_BACKGROUND_GAMMA_UNKNOWN 0
#define PNG_BACKGROUND_GAMMA_SCREEN  1
#define PNG_BACKGROUND_GAMMA_FILE    2
#define PNG_BACKGROUND_GAMMA_UNIQUE  3
#define PNG_READ_16_TO_8_SUPPORTED
#define PNG_GAMMA_THRESHOLD (PNG_GAMMA_THRESHOLD_FIXED*.00001)
#define PNG_CRC_DEFAULT       0
#define PNG_CRC_ERROR_QUIT    1
#define PNG_CRC_WARN_DISCARD  2
#define PNG_CRC_WARN_USE      3
#define PNG_CRC_QUIET_USE     4
#define PNG_CRC_NO_CHANGE     5
#define PNG_NO_FILTERS     0x00
#define PNG_FILTER_NONE    0x08
#define PNG_FILTER_SUB     0x10
#define PNG_FILTER_UP      0x20
#define PNG_FILTER_AVG     0x40
#define PNG_FILTER_PAETH   0x80
#define PNG_FAST_FILTERS (PNG_FILTER_NONE | PNG_FILTER_SUB | PNG_FILTER_UP)
#define PNG_ALL_FILTERS (PNG_FAST_FILTERS | PNG_FILTER_AVG | PNG_FILTER_PAETH)
#define PNG_FILTER_VALUE_NONE  0
#define PNG_FILTER_VALUE_SUB   1
#define PNG_FILTER_VALUE_UP    2
#define PNG_FILTER_VALUE_AVG   3
#define PNG_FILTER_VALUE_PAETH 4
#define PNG_FILTER_VALUE_LAST  5
#define PNG_FILTER_HEURISTIC_DEFAULT    0
#define PNG_FILTER_HEURISTIC_UNWEIGHTED 1
#define PNG_FILTER_HEURISTIC_WEIGHTED   2
#define PNG_FILTER_HEURISTIC_LAST       3
#define PNG_DESTROY_WILL_FREE_DATA 1
#define PNG_SET_WILL_FREE_DATA 1
#define PNG_USER_WILL_FREE_DATA 2
#define PNG_FREE_HIST 0x0008U
#define PNG_FREE_ICCP 0x0010U
#define PNG_FREE_SPLT 0x0020U
#define PNG_FREE_ROWS 0x0040U
#define PNG_FREE_PCAL 0x0080U
#define PNG_FREE_SCAL 0x0100U
#define PNG_FREE_UNKN 0x0200U
#define PNG_FREE_PLTE 0x1000U
#define PNG_FREE_TRNS 0x2000U
#define PNG_FREE_TEXT 0x4000U
#define PNG_FREE_EXIF 0x8000U
#define PNG_FREE_ALL  0xffffU
#define PNG_FREE_MUL  0x4220U
#define png_error(s1,s2) png_err(s1)
#define png_chunk_error(s1,s2) png_err(s1)
#define png_warning(s1,s2) ((void)(s1))
#define png_chunk_warning(s1,s2) ((void)(s1))
#define PNG_HANDLE_CHUNK_AS_DEFAULT   0
#define PNG_HANDLE_CHUNK_NEVER        1
#define PNG_HANDLE_CHUNK_IF_SAFE      2
#define PNG_HANDLE_CHUNK_ALWAYS       3
#define PNG_HANDLE_CHUNK_LAST         4
#define PNG_IO_NONE        0x0000
#define PNG_IO_READING     0x0001
#define PNG_IO_WRITING     0x0002
#define PNG_IO_SIGNATURE   0x0010
#define PNG_IO_CHUNK_HDR   0x0020
#define PNG_IO_CHUNK_DATA  0x0040
#define PNG_IO_CHUNK_CRC   0x0080
#define PNG_IO_MASK_OP     0x000f
#define PNG_IO_MASK_LOC    0x00f0
#define PNG_INTERLACE_ADAM7_PASSES 7
#define PNG_PASS_START_ROW(pass) (((1&~(pass))<<(3-((pass)>>1)))&7)
#define PNG_PASS_START_COL(pass) (((1& (pass))<<(3-(((pass)+1)>>1)))&7)
#define PNG_PASS_ROW_OFFSET(pass) ((pass)>2?(8>>(((pass)-1)>>1)):8)
#define PNG_PASS_COL_OFFSET(pass) (1<<((7-(pass))>>1))
#define PNG_PASS_ROW_SHIFT(pass) ((pass)>2?(8-(pass))>>1:3)
#define PNG_PASS_COL_SHIFT(pass) ((pass)>1?(7-(pass))>>1:3)
#define PNG_IMAGE_VERSION 1
#define PNG_IMAGE_WARNING 1
#define PNG_IMAGE_ERROR 2
#define PNG_IMAGE_FAILED(png_cntrl) ((((png_cntrl).warning_or_error)&0x03)>1)
#define PNG_FORMAT_FLAG_ALPHA    0x01U
#define PNG_FORMAT_FLAG_COLOR    0x02U
#define PNG_FORMAT_FLAG_LINEAR   0x04U
#define PNG_FORMAT_FLAG_COLORMAP 0x08U
#define PNG_FORMAT_FLAG_BGR    0x10U
#define PNG_FORMAT_FLAG_AFIRST 0x20U
#define PNG_FORMAT_FLAG_ASSOCIATED_ALPHA 0x40U
#define PNG_FORMAT_GRAY 0
#define PNG_FORMAT_GA   PNG_FORMAT_FLAG_ALPHA
#define PNG_FORMAT_AG   (PNG_FORMAT_GA|PNG_FORMAT_FLAG_AFIRST)
#define PNG_FORMAT_RGB  PNG_FORMAT_FLAG_COLOR
#define PNG_FORMAT_BGR  (PNG_FORMAT_FLAG_COLOR|PNG_FORMAT_FLAG_BGR)
#define PNG_FORMAT_RGBA (PNG_FORMAT_RGB|PNG_FORMAT_FLAG_ALPHA)
#define PNG_FORMAT_ARGB (PNG_FORMAT_RGBA|PNG_FORMAT_FLAG_AFIRST)
#define PNG_FORMAT_BGRA (PNG_FORMAT_BGR|PNG_FORMAT_FLAG_ALPHA)
#define PNG_FORMAT_ABGR (PNG_FORMAT_BGRA|PNG_FORMAT_FLAG_AFIRST)
#define PNG_FORMAT_LINEAR_Y PNG_FORMAT_FLAG_LINEAR
#define PNG_FORMAT_LINEAR_Y_ALPHA (PNG_FORMAT_FLAG_LINEAR|PNG_FORMAT_FLAG_ALPHA)
#define PNG_FORMAT_LINEAR_RGB (PNG_FORMAT_FLAG_LINEAR|PNG_FORMAT_FLAG_COLOR)
#define PNG_FORMAT_RGB_COLORMAP  (PNG_FORMAT_RGB|PNG_FORMAT_FLAG_COLORMAP)
#define PNG_FORMAT_BGR_COLORMAP  (PNG_FORMAT_BGR|PNG_FORMAT_FLAG_COLORMAP)
#define PNG_FORMAT_RGBA_COLORMAP (PNG_FORMAT_RGBA|PNG_FORMAT_FLAG_COLORMAP)
#define PNG_FORMAT_ARGB_COLORMAP (PNG_FORMAT_ARGB|PNG_FORMAT_FLAG_COLORMAP)
#define PNG_FORMAT_BGRA_COLORMAP (PNG_FORMAT_BGRA|PNG_FORMAT_FLAG_COLORMAP)
#define PNG_FORMAT_ABGR_COLORMAP (PNG_FORMAT_ABGR|PNG_FORMAT_FLAG_COLORMAP)
#define PNG_IMAGE_PIXEL_SIZE(fmt) PNG_IMAGE_PIXEL_(PNG_IMAGE_SAMPLE_SIZE,fmt)
#define PNG_IMAGE_FLAG_COLORSPACE_NOT_sRGB 0x01
#define PNG_IMAGE_FLAG_FAST 0x02
#define PNG_IMAGE_FLAG_16BIT_sRGB 0x04
#define PNG_IMAGE_DATA_SIZE(image) (PNG_IMAGE_SIZE(image)+(image).height)
#define PNG_ZLIB_MAX_SIZE(b) ((b)+(((b)+7U)>>3)+(((b)+63U)>>6)+11U)
#define PNG_ARM_NEON 0
#define PNG_MAXIMUM_INFLATE_WINDOW 2
#define PNG_SKIP_sRGB_CHECK_PROFILE 4
#define PNG_MIPS_MSA 6
#define PNG_IGNORE_ADLER32 8
#define PNG_POWERPC_VSX 10
#define PNG_MIPS_MMI 12
#define PNG_RISCV_RVV 14
#define PNG_OPTION_NEXT 16
#define PNG_OPTION_UNSET   0
#define PNG_OPTION_INVALID 1
#define PNG_OPTION_OFF     2
#define PNG_OPTION_ON      3

#define REMOVE_API(x)

// This macro can apply a macro to all function pointers.
// If you dont want to load some functions, remove "LIBPNG_MAP(png_***) \" from here.
// (or use the REMOVE_API(x) macro.)
// They will be removed from the whole binary of libpng-loader.
// (No need to edit libpng-loader.c!)
// If you dont want to force some functions to be exists, replace LIBPNG_MAP with LIBPNG_OPT.
// They will be ignored when libpng-loader checks fuction pointers.
#define LIBPNG_FUNC_MAPPING \
    REMOVE_API(png_plz_ignore_this_line) \
    LIBPNG_MAP(png_access_version_number) \
    LIBPNG_MAP(png_set_sig_bytes) \
    LIBPNG_MAP(png_sig_cmp) \
    LIBPNG_MAP(png_create_read_struct) \
    LIBPNG_MAP(png_create_write_struct) \
    LIBPNG_MAP(png_get_compression_buffer_size) \
    LIBPNG_MAP(png_set_compression_buffer_size) \
    LIBPNG_MAP(png_set_longjmp_fn) \
    LIBPNG_MAP(png_longjmp) \
    LIBPNG_MAP(png_reset_zstream) \
    LIBPNG_MAP(png_create_read_struct_2) \
    LIBPNG_MAP(png_create_write_struct_2) \
    LIBPNG_MAP(png_write_sig) \
    LIBPNG_MAP(png_write_chunk) \
    LIBPNG_MAP(png_write_chunk_start) \
    LIBPNG_MAP(png_write_chunk_data) \
    LIBPNG_MAP(png_write_chunk_end) \
    LIBPNG_MAP(png_create_info_struct) \
    LIBPNG_MAP(png_info_init_3) \
    LIBPNG_MAP(png_write_info_before_PLTE) \
    LIBPNG_MAP(png_write_info) \
    LIBPNG_MAP(png_read_info) \
    LIBPNG_MAP(png_convert_to_rfc1123) \
    LIBPNG_MAP(png_convert_to_rfc1123_buffer) \
    LIBPNG_MAP(png_convert_from_struct_tm) \
    LIBPNG_MAP(png_convert_from_time_t) \
    LIBPNG_MAP(png_set_expand) \
    LIBPNG_MAP(png_set_expand_gray_1_2_4_to_8) \
    LIBPNG_MAP(png_set_palette_to_rgb) \
    LIBPNG_MAP(png_set_tRNS_to_alpha) \
    LIBPNG_MAP(png_set_expand_16) \
    LIBPNG_MAP(png_set_bgr) \
    LIBPNG_MAP(png_set_gray_to_rgb) \
    LIBPNG_MAP(png_set_rgb_to_gray) \
    LIBPNG_MAP(png_set_rgb_to_gray_fixed) \
    LIBPNG_MAP(png_get_rgb_to_gray_status) \
    LIBPNG_MAP(png_build_grayscale_palette) \
    LIBPNG_MAP(png_set_alpha_mode) \
    LIBPNG_MAP(png_set_alpha_mode_fixed) \
    LIBPNG_MAP(png_set_strip_alpha) \
    LIBPNG_MAP(png_set_swap_alpha) \
    LIBPNG_MAP(png_set_invert_alpha) \
    LIBPNG_MAP(png_set_filler) \
    LIBPNG_MAP(png_set_add_alpha) \
    LIBPNG_MAP(png_set_swap) \
    LIBPNG_MAP(png_set_packing) \
    LIBPNG_MAP(png_set_packswap) \
    LIBPNG_MAP(png_set_shift) \
    LIBPNG_MAP(png_set_interlace_handling) \
    LIBPNG_MAP(png_set_invert_mono) \
    LIBPNG_MAP(png_set_background) \
    LIBPNG_MAP(png_set_background_fixed) \
    LIBPNG_MAP(png_set_scale_16) \
    LIBPNG_MAP(png_set_strip_16) \
    LIBPNG_MAP(png_set_quantize) \
    LIBPNG_MAP(png_set_gamma) \
    LIBPNG_MAP(png_set_gamma_fixed) \
    LIBPNG_MAP(png_set_flush) \
    LIBPNG_MAP(png_write_flush) \
    LIBPNG_MAP(png_start_read_image) \
    LIBPNG_MAP(png_read_update_info) \
    LIBPNG_MAP(png_read_rows) \
    LIBPNG_MAP(png_read_row) \
    LIBPNG_MAP(png_read_image) \
    LIBPNG_MAP(png_write_row) \
    LIBPNG_MAP(png_write_rows) \
    LIBPNG_MAP(png_write_image) \
    LIBPNG_MAP(png_write_end) \
    LIBPNG_MAP(png_read_end) \
    LIBPNG_MAP(png_destroy_info_struct) \
    LIBPNG_MAP(png_destroy_read_struct) \
    LIBPNG_MAP(png_destroy_write_struct) \
    LIBPNG_MAP(png_set_crc_action) \
    LIBPNG_MAP(png_set_filter) \
    LIBPNG_MAP(png_set_filter_heuristics) \
    LIBPNG_MAP(png_set_filter_heuristics_fixed) \
    LIBPNG_MAP(png_set_compression_level) \
    LIBPNG_MAP(png_set_compression_mem_level) \
    LIBPNG_MAP(png_set_compression_strategy) \
    LIBPNG_MAP(png_set_compression_window_bits) \
    LIBPNG_MAP(png_set_compression_method) \
    LIBPNG_MAP(png_set_text_compression_level) \
    LIBPNG_MAP(png_set_text_compression_mem_level) \
    LIBPNG_MAP(png_set_text_compression_strategy) \
    LIBPNG_MAP(png_set_text_compression_window_bits) \
    LIBPNG_MAP(png_set_text_compression_method) \
    LIBPNG_MAP(png_init_io) \
    LIBPNG_MAP(png_set_error_fn) \
    LIBPNG_MAP(png_get_error_ptr) \
    LIBPNG_MAP(png_set_write_fn) \
    LIBPNG_MAP(png_set_read_fn) \
    LIBPNG_MAP(png_get_io_ptr) \
    LIBPNG_MAP(png_set_read_status_fn) \
    LIBPNG_MAP(png_set_write_status_fn) \
    LIBPNG_MAP(png_set_mem_fn) \
    LIBPNG_MAP(png_get_mem_ptr) \
    LIBPNG_MAP(png_set_read_user_transform_fn) \
    LIBPNG_MAP(png_set_write_user_transform_fn) \
    LIBPNG_MAP(png_set_user_transform_info) \
    LIBPNG_MAP(png_get_user_transform_ptr) \
    LIBPNG_MAP(png_get_current_row_number) \
    LIBPNG_MAP(png_get_current_pass_number) \
    LIBPNG_MAP(png_set_read_user_chunk_fn) \
    LIBPNG_MAP(png_get_user_chunk_ptr) \
    LIBPNG_MAP(png_set_progressive_read_fn) \
    LIBPNG_MAP(png_get_progressive_ptr) \
    LIBPNG_MAP(png_process_data) \
    LIBPNG_MAP(png_process_data_pause) \
    LIBPNG_MAP(png_process_data_skip) \
    LIBPNG_MAP(png_progressive_combine_row) \
    LIBPNG_MAP(png_malloc) \
    LIBPNG_MAP(png_calloc) \
    LIBPNG_MAP(png_malloc_warn) \
    LIBPNG_MAP(png_free) \
    LIBPNG_MAP(png_free_data) \
    LIBPNG_MAP(png_data_freer) \
    LIBPNG_MAP(png_malloc_default) \
    LIBPNG_MAP(png_free_default) \
    LIBPNG_MAP(png_error) \
    LIBPNG_MAP(png_chunk_error) \
    LIBPNG_OPT(png_err) \
    LIBPNG_MAP(png_warning) \
    LIBPNG_MAP(png_chunk_warning) \
    LIBPNG_MAP(png_benign_error) \
    LIBPNG_MAP(png_chunk_benign_error) \
    LIBPNG_MAP(png_set_benign_errors) \
    LIBPNG_MAP(png_get_valid) \
    LIBPNG_MAP(png_get_rowbytes) \
    LIBPNG_MAP(png_get_rows) \
    LIBPNG_MAP(png_set_rows) \
    LIBPNG_MAP(png_get_channels) \
    LIBPNG_MAP(png_get_image_width) \
    LIBPNG_MAP(png_get_image_height) \
    LIBPNG_MAP(png_get_bit_depth) \
    LIBPNG_MAP(png_get_color_type) \
    LIBPNG_MAP(png_get_filter_type) \
    LIBPNG_MAP(png_get_interlace_type) \
    LIBPNG_MAP(png_get_compression_type) \
    LIBPNG_MAP(png_get_pixels_per_meter) \
    LIBPNG_MAP(png_get_x_pixels_per_meter) \
    LIBPNG_MAP(png_get_y_pixels_per_meter) \
    LIBPNG_MAP(png_get_pixel_aspect_ratio) \
    LIBPNG_MAP(png_get_pixel_aspect_ratio_fixed) \
    LIBPNG_MAP(png_get_x_offset_pixels) \
    LIBPNG_MAP(png_get_y_offset_pixels) \
    LIBPNG_MAP(png_get_x_offset_microns) \
    LIBPNG_MAP(png_get_y_offset_microns) \
    LIBPNG_MAP(png_get_signature) \
    LIBPNG_MAP(png_get_bKGD) \
    LIBPNG_MAP(png_set_bKGD) \
    LIBPNG_MAP(png_get_cHRM) \
    LIBPNG_MAP(png_get_cHRM_XYZ) \
    LIBPNG_MAP(png_get_cHRM_fixed) \
    LIBPNG_MAP(png_get_cHRM_XYZ_fixed) \
    LIBPNG_MAP(png_set_cHRM) \
    LIBPNG_MAP(png_set_cHRM_XYZ) \
    LIBPNG_MAP(png_set_cHRM_fixed) \
    LIBPNG_MAP(png_set_cHRM_XYZ_fixed) \
    LIBPNG_OPT(png_get_cICP) \
    LIBPNG_OPT(png_set_cICP) \
    LIBPNG_OPT(png_get_cLLI) \
    LIBPNG_OPT(png_get_cLLI_fixed) \
    LIBPNG_OPT(png_set_cLLI) \
    LIBPNG_OPT(png_set_cLLI_fixed) \
    LIBPNG_OPT(png_get_eXIf) \
    LIBPNG_OPT(png_set_eXIf) \
    LIBPNG_OPT(png_get_eXIf_1) \
    LIBPNG_OPT(png_set_eXIf_1) \
    LIBPNG_MAP(png_get_gAMA) \
    LIBPNG_MAP(png_get_gAMA_fixed) \
    LIBPNG_MAP(png_set_gAMA) \
    LIBPNG_MAP(png_set_gAMA_fixed) \
    LIBPNG_MAP(png_get_hIST) \
    LIBPNG_MAP(png_set_hIST) \
    LIBPNG_MAP(png_get_IHDR) \
    LIBPNG_MAP(png_set_IHDR) \
    LIBPNG_OPT(png_get_mDCV) \
    LIBPNG_OPT(png_get_mDCV_fixed) \
    LIBPNG_OPT(png_set_mDCV) \
    LIBPNG_OPT(png_set_mDCV_fixed) \
    LIBPNG_MAP(png_get_oFFs) \
    LIBPNG_MAP(png_set_oFFs) \
    LIBPNG_MAP(png_get_pCAL) \
    LIBPNG_MAP(png_set_pCAL) \
    LIBPNG_MAP(png_get_pHYs) \
    LIBPNG_MAP(png_set_pHYs) \
    LIBPNG_MAP(png_get_PLTE) \
    LIBPNG_MAP(png_set_PLTE) \
    LIBPNG_MAP(png_get_sBIT) \
    LIBPNG_MAP(png_set_sBIT) \
    LIBPNG_MAP(png_get_sRGB) \
    LIBPNG_MAP(png_set_sRGB) \
    LIBPNG_MAP(png_set_sRGB_gAMA_and_cHRM) \
    LIBPNG_MAP(png_get_iCCP) \
    LIBPNG_MAP(png_set_iCCP) \
    LIBPNG_MAP(png_get_sPLT) \
    LIBPNG_MAP(png_set_sPLT) \
    LIBPNG_MAP(png_get_text) \
    LIBPNG_MAP(png_set_text) \
    LIBPNG_MAP(png_get_tIME) \
    LIBPNG_MAP(png_set_tIME) \
    LIBPNG_MAP(png_get_tRNS) \
    LIBPNG_MAP(png_set_tRNS) \
    LIBPNG_MAP(png_get_sCAL) \
    LIBPNG_MAP(png_get_sCAL_fixed) \
    LIBPNG_MAP(png_get_sCAL_s) \
    LIBPNG_MAP(png_set_sCAL) \
    LIBPNG_MAP(png_set_sCAL_fixed) \
    LIBPNG_MAP(png_set_sCAL_s) \
    LIBPNG_MAP(png_set_keep_unknown_chunks) \
    LIBPNG_MAP(png_handle_as_unknown) \
    LIBPNG_MAP(png_set_unknown_chunks) \
    LIBPNG_MAP(png_set_unknown_chunk_location) \
    LIBPNG_MAP(png_get_unknown_chunks) \
    LIBPNG_MAP(png_set_invalid) \
    LIBPNG_MAP(png_read_png) \
    LIBPNG_MAP(png_write_png) \
    LIBPNG_MAP(png_get_copyright) \
    LIBPNG_MAP(png_get_header_ver) \
    LIBPNG_MAP(png_get_header_version) \
    LIBPNG_MAP(png_get_libpng_ver) \
    LIBPNG_MAP(png_permit_mng_features) \
    LIBPNG_OPT(png_set_strip_error_numbers) \
    LIBPNG_MAP(png_set_user_limits) \
    LIBPNG_MAP(png_get_user_width_max) \
    LIBPNG_MAP(png_get_user_height_max) \
    LIBPNG_MAP(png_set_chunk_cache_max) \
    LIBPNG_MAP(png_get_chunk_cache_max) \
    LIBPNG_MAP(png_set_chunk_malloc_max) \
    LIBPNG_MAP(png_get_chunk_malloc_max) \
    LIBPNG_MAP(png_get_pixels_per_inch) \
    LIBPNG_MAP(png_get_x_pixels_per_inch) \
    LIBPNG_MAP(png_get_y_pixels_per_inch) \
    LIBPNG_MAP(png_get_x_offset_inches) \
    LIBPNG_MAP(png_get_x_offset_inches_fixed) \
    LIBPNG_MAP(png_get_y_offset_inches) \
    LIBPNG_MAP(png_get_y_offset_inches_fixed) \
    LIBPNG_MAP(png_get_pHYs_dpi) \
    LIBPNG_MAP(png_get_io_state) \
    LIBPNG_MAP(png_get_io_chunk_type) \
    LIBPNG_MAP(png_get_uint_32) \
    LIBPNG_MAP(png_get_uint_16) \
    LIBPNG_MAP(png_get_int_32) \
    LIBPNG_MAP(png_get_uint_31) \
    LIBPNG_MAP(png_save_uint_32) \
    LIBPNG_MAP(png_save_int_32) \
    LIBPNG_MAP(png_save_uint_16) \
    LIBPNG_MAP(png_set_check_for_invalid_index) \
    LIBPNG_MAP(png_get_palette_max) \
    LIBPNG_MAP(png_image_begin_read_from_file) \
    LIBPNG_MAP(png_image_begin_read_from_stdio) \
    LIBPNG_MAP(png_image_begin_read_from_memory) \
    LIBPNG_MAP(png_image_finish_read) \
    LIBPNG_MAP(png_image_free) \
    LIBPNG_MAP(png_image_write_to_file) \
    LIBPNG_MAP(png_image_write_to_stdio) \
    LIBPNG_MAP(png_image_write_to_memory) \
    LIBPNG_MAP(png_set_option)

// ------ Callback Types ------

typedef void (*png_error_ptr)(png_struct *, const png_char *);
typedef void (*png_rw_ptr)(png_struct *, png_byte *, size_t);
typedef void (*png_flush_ptr)(png_struct *);
typedef void (*png_read_status_ptr)(png_struct *, png_uint_32, int);
typedef void (*png_write_status_ptr)(png_struct *, png_uint_32, int);
typedef void (*png_progressive_info_ptr)(png_struct *, png_info *);
typedef void (*png_progressive_end_ptr)(png_struct *, png_info *);
typedef void (*png_progressive_row_ptr)(png_struct *, png_byte *, png_uint_32, int);
typedef void (*png_user_transform_ptr)(png_struct *, png_row_info *, png_byte *);
typedef int (*png_user_chunk_ptr)(png_struct *, png_unknown_chunk *);
typedef void (*png_longjmp_ptr)(jmp_buf, int);
typedef png_void * (*png_malloc_ptr)(png_struct *, png_alloc_size_t);
typedef void (*png_free_ptr)(png_struct *, png_void *);

// ------ Function Types ------

typedef png_uint_32 (*PFN_png_access_version_number)(void);
typedef void (*PFN_png_set_sig_bytes)(png_struct *, int);
typedef int (*PFN_png_sig_cmp)(const png_byte *, size_t, size_t);
typedef png_struct * (*PFN_png_create_read_struct)(const png_char *, png_void *, png_error_ptr, png_error_ptr);
typedef png_struct * (*PFN_png_create_write_struct)(const png_char *, png_void *, png_error_ptr, png_error_ptr);
typedef size_t (*PFN_png_get_compression_buffer_size)(const png_struct *);
typedef void (*PFN_png_set_compression_buffer_size)(png_struct *, size_t);
typedef jmp_buf* (*PFN_png_set_longjmp_fn)(png_struct *, png_longjmp_ptr, size_t);
typedef void (*PFN_png_longjmp)(const png_struct *, int);
typedef int (*PFN_png_reset_zstream)(png_struct *);
typedef png_struct * (*PFN_png_create_read_struct_2)(const png_char *, png_void *, png_error_ptr, png_error_ptr, png_void *, png_malloc_ptr, png_free_ptr);
typedef png_struct * (*PFN_png_create_write_struct_2)(const png_char *, png_void *, png_error_ptr, png_error_ptr, png_void *, png_malloc_ptr, png_free_ptr);
typedef void (*PFN_png_write_sig)(png_struct *);
typedef void (*PFN_png_write_chunk)(png_struct *, const png_byte *, const png_byte *, size_t);
typedef void (*PFN_png_write_chunk_start)(png_struct *, const png_byte *, png_uint_32);
typedef void (*PFN_png_write_chunk_data)(png_struct *, const png_byte *, size_t);
typedef void (*PFN_png_write_chunk_end)(png_struct *);
typedef png_info * (*PFN_png_create_info_struct)(const png_struct *);
typedef void (*PFN_png_info_init_3)(png_info **, size_t);
typedef void (*PFN_png_write_info_before_PLTE)(png_struct *, const png_info *);
typedef void (*PFN_png_write_info)(png_struct *, const png_info *);
typedef void (*PFN_png_read_info)(png_struct *, png_info *);
typedef const png_char * (*PFN_png_convert_to_rfc1123)(png_struct *, const png_time *);
typedef int (*PFN_png_convert_to_rfc1123_buffer)(char, const png_time *);
typedef void (*PFN_png_convert_from_struct_tm)(png_time *, const struct tm *);
typedef void (*PFN_png_convert_from_time_t)(png_time *, time_t);
typedef void (*PFN_png_set_expand)(png_struct *);
typedef void (*PFN_png_set_expand_gray_1_2_4_to_8)(png_struct *);
typedef void (*PFN_png_set_palette_to_rgb)(png_struct *);
typedef void (*PFN_png_set_tRNS_to_alpha)(png_struct *);
typedef void (*PFN_png_set_expand_16)(png_struct *);
typedef void (*PFN_png_set_bgr)(png_struct *);
typedef void (*PFN_png_set_gray_to_rgb)(png_struct *);
typedef void (*PFN_png_set_rgb_to_gray)(png_struct *, int, double, double);
typedef void (*PFN_png_set_rgb_to_gray_fixed)(png_struct *, int, png_fixed_point, png_fixed_point);
typedef png_byte (*PFN_png_get_rgb_to_gray_status)(const png_struct *);
typedef void (*PFN_png_build_grayscale_palette)(int, png_color *);
typedef void (*PFN_png_set_alpha_mode)(png_struct *, int, double);
typedef void (*PFN_png_set_alpha_mode_fixed)(png_struct *, int, png_fixed_point);
typedef void (*PFN_png_set_strip_alpha)(png_struct *);
typedef void (*PFN_png_set_swap_alpha)(png_struct *);
typedef void (*PFN_png_set_invert_alpha)(png_struct *);
typedef void (*PFN_png_set_filler)(png_struct *, png_uint_32, int);
typedef void (*PFN_png_set_add_alpha)(png_struct *, png_uint_32, int);
typedef void (*PFN_png_set_swap)(png_struct *);
typedef void (*PFN_png_set_packing)(png_struct *);
typedef void (*PFN_png_set_packswap)(png_struct *);
typedef void (*PFN_png_set_shift)(png_struct *, const png_color_8 *);
typedef int (*PFN_png_set_interlace_handling)(png_struct *);
typedef void (*PFN_png_set_invert_mono)(png_struct *);
typedef void (*PFN_png_set_background)(png_struct *, const png_color_16 *, int, int, double);
typedef void (*PFN_png_set_background_fixed)(png_struct *, const png_color_16 *, int, int, png_fixed_point);
typedef void (*PFN_png_set_scale_16)(png_struct *);
typedef void (*PFN_png_set_strip_16)(png_struct *);
typedef void (*PFN_png_set_quantize)(png_struct *, png_color *, int, int, const png_uint_16 *, int);
typedef void (*PFN_png_set_gamma)(png_struct *, double, double);
typedef void (*PFN_png_set_gamma_fixed)(png_struct *, png_fixed_point, png_fixed_point);
typedef void (*PFN_png_set_flush)(png_struct *, int);
typedef void (*PFN_png_write_flush)(png_struct *);
typedef void (*PFN_png_start_read_image)(png_struct *);
typedef void (*PFN_png_read_update_info)(png_struct *, png_info *);
typedef void (*PFN_png_read_rows)(png_struct *, png_byte **, png_byte **, png_uint_32);
typedef void (*PFN_png_read_row)(png_struct *, png_byte *, png_byte *);
typedef void (*PFN_png_read_image)(png_struct *, png_byte **);
typedef void (*PFN_png_write_row)(png_struct *, const png_byte *);
typedef void (*PFN_png_write_rows)(png_struct *, png_byte **, png_uint_32);
typedef void (*PFN_png_write_image)(png_struct *, png_byte **);
typedef void (*PFN_png_write_end)(png_struct *, png_info *);
typedef void (*PFN_png_read_end)(png_struct *, png_info *);
typedef void (*PFN_png_destroy_info_struct)(const png_struct *, png_info **);
typedef void (*PFN_png_destroy_read_struct)(png_struct **, png_info **, png_info **);
typedef void (*PFN_png_destroy_write_struct)(png_struct **, png_info **);
typedef void (*PFN_png_set_crc_action)(png_struct *, int, int);
typedef void (*PFN_png_set_filter)(png_struct *, int, int);
typedef void (*PFN_png_set_filter_heuristics)(png_struct *, int, int, const png_double *, const png_double *);
typedef void (*PFN_png_set_filter_heuristics_fixed)(png_struct *, int, int, const png_fixed_point *, const png_fixed_point *);
typedef void (*PFN_png_set_compression_level)(png_struct *, int);
typedef void (*PFN_png_set_compression_mem_level)(png_struct *, int);
typedef void (*PFN_png_set_compression_strategy)(png_struct *, int);
typedef void (*PFN_png_set_compression_window_bits)(png_struct *, int);
typedef void (*PFN_png_set_compression_method)(png_struct *, int);
typedef void (*PFN_png_set_text_compression_level)(png_struct *, int);
typedef void (*PFN_png_set_text_compression_mem_level)(png_struct *, int);
typedef void (*PFN_png_set_text_compression_strategy)(png_struct *, int);
typedef void (*PFN_png_set_text_compression_window_bits)(png_struct *, int);
typedef void (*PFN_png_set_text_compression_method)(png_struct *, int);
typedef void (*PFN_png_init_io)(png_struct *, FILE *);
typedef void (*PFN_png_set_error_fn)(png_struct *, png_void *, png_error_ptr, png_error_ptr);
typedef png_void * (*PFN_png_get_error_ptr)(const png_struct *);
typedef void (*PFN_png_set_write_fn)(png_struct *, png_void *, png_rw_ptr, png_flush_ptr);
typedef void (*PFN_png_set_read_fn)(png_struct *, png_void *, png_rw_ptr);
typedef png_void * (*PFN_png_get_io_ptr)(const png_struct *);
typedef void (*PFN_png_set_read_status_fn)(png_struct *, png_read_status_ptr);
typedef void (*PFN_png_set_write_status_fn)(png_struct *, png_write_status_ptr);
typedef void (*PFN_png_set_mem_fn)(png_struct *, png_void *, png_malloc_ptr, png_free_ptr);
typedef png_void * (*PFN_png_get_mem_ptr)(const png_struct *);
typedef void (*PFN_png_set_read_user_transform_fn)(png_struct *, png_user_transform_ptr);
typedef void (*PFN_png_set_write_user_transform_fn)(png_struct *, png_user_transform_ptr);
typedef void (*PFN_png_set_user_transform_info)(png_struct *, png_void *, int, int);
typedef png_void * (*PFN_png_get_user_transform_ptr)(const png_struct *);
typedef png_uint_32 (*PFN_png_get_current_row_number)(const png_struct *);
typedef png_byte (*PFN_png_get_current_pass_number)(const png_struct *);
typedef void (*PFN_png_set_read_user_chunk_fn)(png_struct *, png_void *, png_user_chunk_ptr);
typedef png_void * (*PFN_png_get_user_chunk_ptr)(const png_struct *);
typedef void (*PFN_png_set_progressive_read_fn)(png_struct *, png_void *, png_progressive_info_ptr, png_progressive_row_ptr, png_progressive_end_ptr);
typedef png_void * (*PFN_png_get_progressive_ptr)(const png_struct *);
typedef void (*PFN_png_process_data)(png_struct *, png_info *, png_byte *, size_t);
typedef size_t (*PFN_png_process_data_pause)(png_struct *, int);
typedef png_uint_32 (*PFN_png_process_data_skip)(png_struct *);
typedef void (*PFN_png_progressive_combine_row)(const png_struct *, png_byte *, const png_byte *);
typedef png_void * (*PFN_png_malloc)(const png_struct *, png_alloc_size_t);
typedef png_void * (*PFN_png_calloc)(const png_struct *, png_alloc_size_t);
typedef png_void * (*PFN_png_malloc_warn)(const png_struct *, png_alloc_size_t);
typedef void (*PFN_png_free)(const png_struct *, png_void *);
typedef void (*PFN_png_free_data)(const png_struct *, png_info *, png_uint_32, int);
typedef void (*PFN_png_data_freer)(const png_struct *, png_info *, int, png_uint_32);
typedef png_void * (*PFN_png_malloc_default)(const png_struct *, png_alloc_size_t);
typedef void (*PFN_png_free_default)(const png_struct *, png_void *);
typedef void (*PFN_png_error)(const png_struct *, const png_char *);
typedef void (*PFN_png_chunk_error)(const png_struct *, const png_char *);
typedef void (*PFN_png_err)(const png_struct *);
typedef void (*PFN_png_warning)(const png_struct *, const png_char *);
typedef void (*PFN_png_chunk_warning)(const png_struct *, const png_char *);
typedef void (*PFN_png_benign_error)(const png_struct *, const png_char *);
typedef void (*PFN_png_chunk_benign_error)(const png_struct *, const png_char *);
typedef void (*PFN_png_set_benign_errors)(png_struct *, int);
typedef png_uint_32 (*PFN_png_get_valid)(const png_struct *, const png_info *, png_uint_32);
typedef size_t (*PFN_png_get_rowbytes)(const png_struct *, const png_info *);
typedef png_byte ** (*PFN_png_get_rows)(const png_struct *, const png_info *);
typedef void (*PFN_png_set_rows)(const png_struct *, png_info *, png_byte **);
typedef png_byte (*PFN_png_get_channels)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_image_width)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_image_height)(const png_struct *, const png_info *);
typedef png_byte (*PFN_png_get_bit_depth)(const png_struct *, const png_info *);
typedef png_byte (*PFN_png_get_color_type)(const png_struct *, const png_info *);
typedef png_byte (*PFN_png_get_filter_type)(const png_struct *, const png_info *);
typedef png_byte (*PFN_png_get_interlace_type)(const png_struct *, const png_info *);
typedef png_byte (*PFN_png_get_compression_type)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_pixels_per_meter)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_x_pixels_per_meter)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_y_pixels_per_meter)(const png_struct *, const png_info *);
typedef float (*PFN_png_get_pixel_aspect_ratio)(const png_struct *, const png_info *);
typedef png_fixed_point (*PFN_png_get_pixel_aspect_ratio_fixed)(const png_struct *, const png_info *);
typedef png_int_32 (*PFN_png_get_x_offset_pixels)(const png_struct *, const png_info *);
typedef png_int_32 (*PFN_png_get_y_offset_pixels)(const png_struct *, const png_info *);
typedef png_int_32 (*PFN_png_get_x_offset_microns)(const png_struct *, const png_info *);
typedef png_int_32 (*PFN_png_get_y_offset_microns)(const png_struct *, const png_info *);
typedef const png_byte * (*PFN_png_get_signature)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_bKGD)(const png_struct *, png_info *, png_color_16 * *);
typedef void (*PFN_png_set_bKGD)(const png_struct *, png_info *, const png_color_16 *);
typedef png_uint_32 (*PFN_png_get_cHRM)(const png_struct *, const png_info *, double *, double *, double *, double *, double *, double *, double *, double *);
typedef png_uint_32 (*PFN_png_get_cHRM_XYZ)(const png_struct *, const png_info *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
typedef png_uint_32 (*PFN_png_get_cHRM_fixed)(const png_struct *, const png_info *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *);
typedef png_uint_32 (*PFN_png_get_cHRM_XYZ_fixed)(const png_struct *, const png_info *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *);
typedef void (*PFN_png_set_cHRM)(const png_struct *, png_info *, double, double, double, double, double, double, double, double);
typedef void (*PFN_png_set_cHRM_XYZ)(const png_struct *, png_info *, double, double, double, double, double, double, double, double, double);
typedef void (*PFN_png_set_cHRM_fixed)(const png_struct *, png_info *, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point);
typedef void (*PFN_png_set_cHRM_XYZ_fixed)(const png_struct *, png_info *, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point);
typedef png_uint_32 (*PFN_png_get_cICP)(const png_struct *, const png_info *, png_byte *, png_byte *, png_byte *, png_byte *);
typedef void (*PFN_png_set_cICP)(const png_struct *, png_info *, png_byte, png_byte, png_byte, png_byte);
typedef png_uint_32 (*PFN_png_get_cLLI)(const png_struct *, const png_info *, double *, double *);
typedef png_uint_32 (*PFN_png_get_cLLI_fixed)(const png_struct *, const png_info *, png_uint_32 *, png_uint_32 *);
typedef void (*PFN_png_set_cLLI)(const png_struct *, png_info *, double, double);
typedef void (*PFN_png_set_cLLI_fixed)(const png_struct *, png_info *, png_uint_32, png_uint_32);
typedef png_uint_32 (*PFN_png_get_eXIf)(const png_struct *, png_info *, png_byte * *);
typedef void (*PFN_png_set_eXIf)(const png_struct *, png_info *, png_byte *);
typedef png_uint_32 (*PFN_png_get_eXIf_1)(const png_struct *, const png_info *, png_uint_32 *, png_byte * *);
typedef void (*PFN_png_set_eXIf_1)(const png_struct *, png_info *, png_uint_32, png_byte *);
typedef png_uint_32 (*PFN_png_get_gAMA)(const png_struct *, const png_info *, double *);
typedef png_uint_32 (*PFN_png_get_gAMA_fixed)(const png_struct *, const png_info *, png_fixed_point *);
typedef void (*PFN_png_set_gAMA)(const png_struct *, png_info *, double);
typedef void (*PFN_png_set_gAMA_fixed)(const png_struct *, png_info *, png_fixed_point);
typedef png_uint_32 (*PFN_png_get_hIST)(const png_struct *, png_info *, png_uint_16 * *);
typedef void (*PFN_png_set_hIST)(const png_struct *, png_info *, const png_uint_16 *);
typedef png_uint_32 (*PFN_png_get_IHDR)(const png_struct *, const png_info *, png_uint_32 *, png_uint_32 *, int *, int *, int *, int *, int *);
typedef void (*PFN_png_set_IHDR)(const png_struct *, png_info *, png_uint_32, png_uint_32, int, int, int, int, int);
typedef png_uint_32 (*PFN_png_get_mDCV)(const png_struct *, const png_info *, double *, double *, double *, double *, double *, double *, double *, double *, double *, double *);
typedef png_uint_32 (*PFN_png_get_mDCV_fixed)(const png_struct *, const png_info *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_fixed_point *, png_uint_32 *, png_uint_32 *);
typedef void (*PFN_png_set_mDCV)(const png_struct *, png_info *, double, double, double, double, double, double, double, double, double, double);
typedef void (*PFN_png_set_mDCV_fixed)(const png_struct *, png_info *, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_fixed_point, png_uint_32, png_uint_32);
typedef png_uint_32 (*PFN_png_get_oFFs)(const png_struct *, const png_info *, png_int_32 *, png_int_32 *, int *);
typedef void (*PFN_png_set_oFFs)(const png_struct *, png_info *, png_int_32, png_int_32, int);
typedef png_uint_32 (*PFN_png_get_pCAL)(const png_struct *, png_info *, png_char * *, png_int_32 *, png_int_32 *, int *, int *, png_char * *, png_char ** *);
typedef void (*PFN_png_set_pCAL)(const png_struct *, png_info *, const png_char *, png_int_32, png_int_32, int, int, const png_char *, png_char **);
typedef png_uint_32 (*PFN_png_get_pHYs)(const png_struct *, const png_info *, png_uint_32 *, png_uint_32 *, int *);
typedef void (*PFN_png_set_pHYs)(const png_struct *, png_info *, png_uint_32, png_uint_32, int);
typedef png_uint_32 (*PFN_png_get_PLTE)(const png_struct *, png_info *, png_color * *, int *);
typedef void (*PFN_png_set_PLTE)(png_struct *, png_info *, const png_color *, int);
typedef png_uint_32 (*PFN_png_get_sBIT)(const png_struct *, png_info *, png_color_8 * *);
typedef void (*PFN_png_set_sBIT)(const png_struct *, png_info *, const png_color_8 *);
typedef png_uint_32 (*PFN_png_get_sRGB)(const png_struct *, const png_info *, int *);
typedef void (*PFN_png_set_sRGB)(const png_struct *, png_info *, int);
typedef void (*PFN_png_set_sRGB_gAMA_and_cHRM)(const png_struct *, png_info *, int);
typedef png_uint_32 (*PFN_png_get_iCCP)(const png_struct *, png_info *, png_char **, int *, png_byte **, png_uint_32 *);
typedef void (*PFN_png_set_iCCP)(const png_struct *, png_info *, const png_char *, int, const png_byte *, png_uint_32);
typedef int (*PFN_png_get_sPLT)(const png_struct *, png_info *, png_sPLT_t **);
typedef void (*PFN_png_set_sPLT)(const png_struct *, png_info *, const png_sPLT_t *, int);
typedef int (*PFN_png_get_text)(const png_struct *, png_info *, png_text * *, int *);
typedef void (*PFN_png_set_text)(const png_struct *, png_info *, const png_text *, int);
typedef png_uint_32 (*PFN_png_get_tIME)(const png_struct *, png_info *, png_time * *);
typedef void (*PFN_png_set_tIME)(const png_struct *, png_info *, const png_time *);
typedef png_uint_32 (*PFN_png_get_tRNS)(const png_struct *, png_info *, png_byte * *, int *, png_color_16 * *);
typedef void (*PFN_png_set_tRNS)(png_struct *, png_info *, const png_byte *, int, const png_color_16 *);
typedef png_uint_32 (*PFN_png_get_sCAL)(const png_struct *, const png_info *, int *, double *, double *);
typedef png_uint_32 (*PFN_png_get_sCAL_fixed)(const png_struct *, const png_info *, int *, png_fixed_point *, png_fixed_point *);
typedef png_uint_32 (*PFN_png_get_sCAL_s)(const png_struct *, const png_info *, int *, png_char **, png_char **);
typedef void (*PFN_png_set_sCAL)(const png_struct *, png_info *, int, double, double);
typedef void (*PFN_png_set_sCAL_fixed)(const png_struct *, png_info *, int, png_fixed_point, png_fixed_point);
typedef void (*PFN_png_set_sCAL_s)(const png_struct *, png_info *, int, const png_char *, const png_char *);
typedef void (*PFN_png_set_keep_unknown_chunks)(png_struct *, int, const png_byte *, int);
typedef int (*PFN_png_handle_as_unknown)(const png_struct *, const png_byte *);
typedef void (*PFN_png_set_unknown_chunks)(const png_struct *, png_info *, const png_unknown_chunk *, int);
typedef void (*PFN_png_set_unknown_chunk_location)(const png_struct *, png_info *, int, int);
typedef int (*PFN_png_get_unknown_chunks)(const png_struct *, png_info *, png_unknown_chunk **);
typedef void (*PFN_png_set_invalid)(const png_struct *, png_info *, int);
typedef void (*PFN_png_read_png)(png_struct *, png_info *, int, png_void *);
typedef void (*PFN_png_write_png)(png_struct *, png_info *, int, png_void *);
typedef const png_char * (*PFN_png_get_copyright)(const png_struct *);
typedef const png_char * (*PFN_png_get_header_ver)(const png_struct *);
typedef const png_char * (*PFN_png_get_header_version)(const png_struct *);
typedef const png_char * (*PFN_png_get_libpng_ver)(const png_struct *);
typedef png_uint_32 (*PFN_png_permit_mng_features)(png_struct *, png_uint_32);
typedef void (*PFN_png_set_strip_error_numbers)(png_struct *, png_uint_32);
typedef void (*PFN_png_set_user_limits)(png_struct *, png_uint_32, png_uint_32);
typedef png_uint_32 (*PFN_png_get_user_width_max)(const png_struct *);
typedef png_uint_32 (*PFN_png_get_user_height_max)(const png_struct *);
typedef void (*PFN_png_set_chunk_cache_max)(png_struct *, png_uint_32);
typedef png_uint_32 (*PFN_png_get_chunk_cache_max)(const png_struct *);
typedef void (*PFN_png_set_chunk_malloc_max)(png_struct *, png_alloc_size_t);
typedef png_alloc_size_t (*PFN_png_get_chunk_malloc_max)(const png_struct *);
typedef png_uint_32 (*PFN_png_get_pixels_per_inch)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_x_pixels_per_inch)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_y_pixels_per_inch)(const png_struct *, const png_info *);
typedef float (*PFN_png_get_x_offset_inches)(const png_struct *, const png_info *);
typedef png_fixed_point (*PFN_png_get_x_offset_inches_fixed)(const png_struct *, const png_info *);
typedef float (*PFN_png_get_y_offset_inches)(const png_struct *, const png_info *);
typedef png_fixed_point (*PFN_png_get_y_offset_inches_fixed)(const png_struct *, const png_info *);
typedef png_uint_32 (*PFN_png_get_pHYs_dpi)(const png_struct *, const png_info *, png_uint_32 *, png_uint_32 *, int *);
typedef png_uint_32 (*PFN_png_get_io_state)(const png_struct *);
typedef png_uint_32 (*PFN_png_get_io_chunk_type)(const png_struct *);
typedef png_uint_32 (*PFN_png_get_uint_32)(const png_byte *);
typedef png_uint_16 (*PFN_png_get_uint_16)(const png_byte *);
typedef png_int_32 (*PFN_png_get_int_32)(const png_byte *);
typedef png_uint_32 (*PFN_png_get_uint_31)(const png_struct *, const png_byte *);
typedef void (*PFN_png_save_uint_32)(png_byte *, png_uint_32);
typedef void (*PFN_png_save_int_32)(png_byte *, png_int_32);
typedef void (*PFN_png_save_uint_16)(png_byte *, unsigned int);
typedef void (*PFN_png_set_check_for_invalid_index)(png_struct *, int);
typedef int (*PFN_png_get_palette_max)(const png_struct *, const png_info *);
typedef int (*PFN_png_image_begin_read_from_file)(png_image *, const char *);
typedef int (*PFN_png_image_begin_read_from_stdio)(png_image *, FILE *);
typedef int (*PFN_png_image_begin_read_from_memory)(png_image *, const png_void *, size_t);
typedef int (*PFN_png_image_finish_read)(png_image *, const png_color *, void *, png_int_32, void *);
typedef void (*PFN_png_image_free)(png_image *);
typedef int (*PFN_png_image_write_to_file)(png_image *, const char *, int, const void *, png_int_32, const void *);
typedef int (*PFN_png_image_write_to_stdio)(png_image *, FILE *, int, const void *, png_int_32, const void *);
typedef int (*PFN_png_image_write_to_memory)(png_image *, void *, png_alloc_size_t *, int, const void *, png_int_32, const void *);
typedef int (*PFN_png_set_option)(png_struct *, int, int);

// ------ Function Pointers ------

// declare all function pointers
#define LIBPNG_MAP(func) extern PFN_##func func;
#define LIBPNG_OPT(func) LIBPNG_MAP(func)
LIBPNG_FUNC_MAPPING
#undef LIBPNG_MAP
#undef LIBPNG_OPT

#endif  // LIBPNG_LOADER_H
